### ISSUE TITLE
Setup the front project

### ISSUE THREAD

**Issue by bellangerq** [bellangerq/poule-poule#4]
- Create the project in `/client`.
- Install `create-react-app`(with typescript).
- Jest
- Sass

Architecture [is here](https://github.com/bellangerq/poule-poule/wiki/Architecture).

**Comment by hissalht** [comment]
Todo list:
- [ ] create-react-app
- [ ] SCSS
- [ ] (CSS modules, to discuss)
- [ ] eslint, prettier
- [ ] testing
- [ ] precommit hooks
